# Generated by Django 5.2.12 on 2026-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apodo', models.CharField(blank=True, max_length=150)),
                ('casa', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=150)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
